files:
  - source: /messages.pot
    translation: /translations/%osx_locale%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      - osx_locale:
          - zh-Hans: zh_Hans
            zh-Hant: zh_Hant
